version: '3.3'
services:
    web:
        build: './web'
        ports:
            - "3000:3000"

    order:
        build: './order'
        ports:
            - "3001:3000"
        depends_on:
            - db
        environment:
            - MONGO_DB_URI=mongodb://db/ordering_sys
    
    payment:
        build: './payment'
        ports:
            - "3002:3000"
        depends_on:
            - db
        environment:
            - MONGO_DB_URI=mongodb://db/ordering_sys
    
    db:
        image: mongo
        ports:
            - "27017:27017"

    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./web/public:/srv/www/static
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - order
            - payment